packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@nestjs/core": false
  "@prisma/engines": true
  "@scarf/scarf": false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 1440

peerDependencyRules:
  allowedVersions:
    "openapi-typescript>typescript": "6.0.3"
